### PR TITLE
Fix duplicate configuration key 'file'

### LINKED ISSUE #5: New target param in 1.1 causes plug in to fail
The new target param added in the last release broke my update_settings_bundle fastlane plugin. Have already verified it works with 1.0 and fails after upgrading to 1.1. The issue is that the new param's key to fastlane is a duplicate of an existing key 'file':

```
FastlaneCore::ConfigItem.new(key: :file,
            env_name: "SETTINGS_BUNDLE_TARGET",
            description: "An optional target name from the project",
            optional: true,
            type: String)
```
I believe the key: should be key: :target instead of :file since :file is an existing param in 1.0

### PR DESCRIPTION
**Pull request by jeff-jk**
Fixes issue #5 
@jdee

### CODE REVIEW

**Comment by jeff-jk** [comment]
Thanks @jdee, do you plan to cut a new release?

**Comment by jdee** [comment]
@jeff-jk Yes. Thanks for the PR, and for using the plugin. I fixed the problem as well and added some unit tests. I'll release this momentarily.

**Comment by jeff-jk** [comment]
Great, thanks a lot for creating this plugin! :1st_place_medal:

**Comment by jdee** [comment]
1.1.1 was released with this fix.

**Comment by jeff-jk** [comment]
Tested and verified, thanks again @jdee.

**Pull request merged**
